version: '3.8'

services:
  backend-llm:
    build: ./backend-python-llm
    container_name: spikifi-llm
    ports:
      - "8000:8000"
    env_file:
      - ./backend-python-llm/.env
    depends_on:
      - mysql

  backend-ml:
    build: ./backend-python-ml
    container_name: spikifi-ml
    ports:
      - "8500:8500"
    env_file:
      - ./backend-python-ml/.env
    depends_on:
      - mysql

  backend-java:
    build: ./backend-java
    container_name: spikifi-java
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build: ./frontend-react
    container_name: spikifi-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  mysql:
    image: mysql:8
    container_name: spikifi-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: fxdata
      MYSQL_USER: spiki
      MYSQL_PASSWORD: spiki123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
